const allowedNPCs = new Set([
    "Scion",
    "Jack",
    "Goddess",
    "Marauder",
    "Ranger",
    "Witch",
    "Duelist",
    "Shadow",
    "Templar",
    "Bestel",
    "Brutus, the Warden",
    "Captain Fairgraves",
    "Damp Diary",
    "Doorman",
    "Dying Exile",
    "Letter of Instruction",
    "Letters of Exile",
    "Lioneye's Standard",
    "Merveil",
    "Nessa",
    "Order of Protection",
    "Sailor's Skin",
    "Shavronne's Journal",
    "Tarkleigh",
    "Weathered Carving",
    "Alira",
    "Ancient Reverie Device",
    "Arteri's Letter",
    "Definitely Oak",
    "Eramir",
    "Etchings on Wood I",
    "Etchings on Wood II",
    "Etchings on Wood III",
    "Etchings on Wood IV",
    "Greust",
    "Helena",
    "Inscription",
    "Kraityn",
    "Oak",
    "Plaque",
    "Proclamation",
    "Silk",
    "Transmutia Device",
    "Yeena",
    "Ancient Graffiti",
    "Ancient Notebook",
    "Clarissa",
    "Grigor",
    "Hargan",
    "Journal Entry",
    "Lady Dialla",
    "Letter to Chitus",
    "Malachai's Journal",
    "Maramoa",
    "Reverie Device",
    "Siosa",
    "The Ancients",
    "The Purity Chronicles",
    "Tolman",
    "Victario's Writings",
    "Dominus",
    "Gravicius",
    "Kira",
    "Malachai's Dedication",
    "Malachai's Notebook",
    "Note",
    "Oyun",
    "Petarus and Vanja",
    "Piety",
    "Resonator Instructions",
    "Tasuni",
    "Voll's Confession",
    "King Kaom",
    "Barkhul",
    "Maligaro, the Inquisitor",
    "Shavronne",
    "Daresso",
    "Malachai",
    "Voll, Emperor of Purity",
    "Avarius",
    "Bannon",
    "Innocence",
    "Kitava's Hunger I",
    "Kitava's Hunger II",
    "Kitava's Hunger III",
    "Lani",
    "Lilly Roth",
    "Sin",
    "Stained Glass Window",
    "Triumph of Innocence",
    "Utula",
    "Vilenta",
    "Karui Carving",
    "Leatherbound Logbook",
    "Letter Fragment",
    "Message in a Bottle",
    "Primitive Carving",
    "Shavronne's Manifesto",
    "Shrine to the Brine King",
    "Templar Report",
    "Tukohama",
    "Weylam Roth",
    "Worn Carving",
    "Love Letter",
    "Maligaro's Manifesto",
    "Ode to Ralakesh",
    "Shrine to Arakaali",
    "Doedre's Manifesto",
    "Lunaris Statue",
    "Official Orders",
    "Solaris Statue",
    "Solaris",
    "Lunaris",
    "Irasha",
    "Cultist Tract",
    "Commander Kirac",
    "Gareth, Serpent Extract Distributor",
    "Tujen, the Harbourmaster",
    "Rog, the Disenchanter",
    "Dannig, the Blacksmith",
    "The Black Knight",
    "Faustus, the Financier",
    "Sasan, the Bandit Lord",
    "Raulf, the Recruiter",
    "Sonja, the Farmer",
    "Johan, the King's Hand",
    "Pirate",
    "Admiral Valerius",
    "Undertaker Arimor",
    "The Warden of Eaves",
    "The Breaker of Oaths",
    "The Primal Huntress",
    "The King in the Mists",
    "Nameless Seer",
    "Kalguuran Shoveller",
    "Kalguuran Blacksmith",
    "Chieftain Ancestor",
    "Rakiata",
    "Maata",
    "Kiloava",
    "Ikiaho",
    "Kahuturoa",
    "Ahuana",
    "Akoya",
    "Tawhanuku",
    "Hinekora",
    "Bronze Monograph",
    "Bronze Plaque",
    "Bronze Inscription",
    "Poem",
    "Izaro",
    "Kadaris, Crimson Mayor",
    "Captain Clayborne, The Accursed",
    "Ara, Sister of Light",
    "Khor, Sister of Shadows",
    "Ormud, Fiend of the Flood",
    "Renkarr, The Kiln Keeper",
    "Ciergan, Shadow Alchemist",
    "Divinia",
    "Lycia",
    "Lycia, Herald of the Scourge",
    "Lycia, Unholy Heretic",
    "Forbidden Knowledge",
    "Beidat",
    "Isolation",
    "Kalandra",
    "Mysterious Voice",
    "Ancient Etchings I",
    "Ancient Etchings II",
    "Ancient Etchings III",
    "Ancient Etchings IV",
    "Ancient Etchings V",
    "Ancient Etchings VI",
    "Ancient Etchings VII",
    "The Searing Exarch",
    "The Eater of Worlds",
    "The Black Star",
    "The Infinite Hunger",
    "The Last to Die",
    "Gwennen, the Gambler",
    "Tujen, the Haggler",
    "Rog, the Dealer",
    "Dannig, Warrior Skald",
    "Medved, Feller of Heroes",
    "Vorana, Last to Fall",
    "Uhtred, Covetous Traitor",
    "Olroth, Origin of the Fall",
    "The Trialmaster",
    "Kurai, the Administrator",
    "Adiyah, the Wayfinder",
    "Faustus, the Fence",
    "Gianna, the Master of Disguise",
    "Huck, the Soldier",
    "Isla, the Engineer",
    "Karst, the Lockpick",
    "Nenet, the Scout",
    "Niles, the Interrogator",
    "Tibbs, the Giant",
    "Tullina, the Catburglar",
    "Vinderi, the Dismantler",
    "Admiral Darnaw",
    "Friedrich Tarollo, Slave Merchant",
    "Jamanra, The Great",
    "Julius Farrow",
    "Nashta, The Usurper",
    "Vic Vox",
    "Vinny Vox",
    "Whakano, the Barber",
    "Water Goddess",
    "The Maven",
    "The Envoy",
    "Oshabi",
    "Strange Voice",
    "Tane Octavius",
    "Crumpled Note",
    "Sirus, Awakener of Worlds",
    "Drox, the Warlord",
    "Al-Hezmin, the Hunter",
    "Veritania, the Redeemer",
    "Baran, the Crusader",
    "Al-Hezmin's Journal I",
    "Al-Hezmin's Journal II",
    "Al-Hezmin's Journal III",
    "Al-Hezmin's Journal IV",
    "Baran's Journal I",
    "Baran's Journal II",
    "Baran's Journal III",
    "Baran's Journal IV",
    "Drox's Journal I",
    "Drox's Journal II",
    "Drox's Journal III",
    "Drox's Journal IV",
    "Veritania's Journal I",
    "Veritania's Journal II",
    "Veritania's Journal III",
    "Veritania's Journal IV",
    "Sirus' Journal I",
    "Sirus' Journal II",
    "Sirus' Journal III",
    "Sirus' Journal IV",
    "Sister Cassia",
    "Queen Hyrri Ngamaku",
    "General Marceus Lioneye",
    "Aukuna, the Black Sekhema",
    "Viper Napuatzi",
    "Cardinal Sanctus Vox",
    "Cavas, Forgotten Spirit",
    "Venarius",
    "Jun, Veiled Master",
    "Vagan, Victory's Herald",
    "Haku, Warmaster",
    "It That Fled",
    "Thane Jorgin the Banished",
    "Aisling Laffrey, The Silent Butcher",
    "Cameria the Coldblooded",
    "Elreon, Light's Judge",
    "Tora, the Culler",
    "Vorici, Silent Brother",
    "Guff \"Tiny\" Grenn",
    "Janus Perandus",
    "Hillock, the Blacksmith",
    "Riker Maloney, Midnight Tinkerer",
    "Korell Goya, Son of Stone",
    "Rin Yuushu",
    "Leo, Wolf of the Pits",
    "Gravicius Reborn",
    "Catarina, Master of Undeath",
    "Lifegiver's Manifesto 1",
    "Lifegiver's Manifesto 2",
    "Lifegiver's Manifesto 3",
    "Lifegiver's Manifesto 4",
    "Lifegiver's Manifesto 5",
    "Niko, Master of the Depths",
    "Aul, the Crystal King",
    "Ahuatotli, the Blind",
    "Alva, Master Explorer",
    "Einhar, Beastmaster",
    "The Shaper",
    "Zana, Master Cartographer",
    "Officer Kirac",
    "Memory Fragment",
    "Book of Memories",
    "Navali",
    "Dark Tome",
    "Cadiro Perandus",
    "Rigwald",
    "Haku, Armourmaster",
    "Elreon, Loremaster",
    "Catarina, Master of the Dead",
    "Vorici, Master Assassin",
    "Tora, Master of the Hunt",
    "Vagan, Weaponmaster",
    "Leo, Master of the Arena",
    "Krillson, Master Fisherman",
    "Daughter of Sin",
    "Freya",
    "Hasina",
    "Skadi",
    "Mel",
    "Isi Thavarra",
    "Research Journal",
    "Vaal Letter",
    "Atziri, Queen of the Vaal",
    "Tutorial NPC",
    "Royale Announcer",
    "Blade Soul",
    "Lieutenant",
    "Remembrance",
    "The Templars",
    "Creations",
    "Capture",
    "Sustenance",
    "Immortality",
    "Chaos Entity",
    "The Molten One",
    "The Redblade Caldera",
    "An Unlikely Alliance",
    "Kosis, the Chained",
    "Ghostrider",
    "Lost Etching",
    "Aided Etching",
    "Compelling Etching",
    "Whispering Etching",
    "Deafened Etching",
    "The Porcelain Queen",
    "Experimental Harvest",
    "Wildwood Greeting",
    "Maji Proclamation",
    "The Exquisite Light of Meaning",
    "Determination",
    "Statue of the Goddess",
    "Worn Statue",
    "The Warring Sisters",
    "Eldritch Hunger",
    "Squire",
    "Mercenary",
    "Monk",
    "Druid",
    "Sorceress",
    "Warrior",
    "Mar",
    "Huntress",
    "Dex",
    "Dex_4_14A",
    "Dex_4_14B",
    "Dex_4_28A",
    "Dex_4_34A",
    "Int_4_G",
    "Dex_4_IncendiaryBoltsRandom",
    "Dex_4_IncendiaryBolts",
    "Dex_4_ArmourPiercingBoltsRandom",
    "Dex_4_ArmourPiercingBolts",
    "Dex_4_PermafrostBoltsRandom",
    "Dex_4_PermafrostBolts",
    "Oba",
    "Asinia's Proclamation",
    "Beira of the Rotten Pack",
    "Brutal Orders",
    "Clearfell Guard",
    "Count's Decree",
    "Count's Orders",
    "Count's Sentencing",
    "Draven's Dictum",
    "Eamon",
    "Escort",
    "Finn",
    "Geonor's Journal",
    "Grieving Epitaph",
    "Lachlann the Lost",
    "Lachlann's Letter",
    "Leitis",
    "Mysterious Orders",
    "Notice of Amnesty",
    "Notice of Criminality",
    "Psalm of Madness",
    "Renly",
    "Rusted Grave",
    "Savvy Letter",
    "Sorrowful Memoriam",
    "The Executioner",
    "The Hooded One",
    "The Way Out",
    "Una",
    "Wounded Man",
    "Zanas Necklace",
    "[DNT] Glyph",
    "Abandoned Rhoa",
    "Azarian, the Forsaken Son",
    "Balbala",
    "Balbala, the Advisor",
    "Book of Jamanra",
    "Decree of Imprisonment",
    "Desert Map",
    "Desperate Message",
    "Etchings of Varashta",
    "Final Testament",
    "Gweinth",
    "Halani, the Water Goddess",
    "Ivory Curio",
    "Jamanra, the Abomination",
    "Jamanra, the Risen King",
    "Lark",
    "Maraketh Tale-Woman",
    "Maraketh Wise Woman",
    "Risu",
    "Risu, Faridun Defector",
    "Sekhema Asala",
    "Shambrin",
    "Testament of Defiance",
    "The Water Goddess",
    "Wayfarer's Stone",
    "Zarka",
    "[DNT] Maraketh Caravan Guard 1",
    "[DNT] Maraketh Caravan Guard 2",
    "Alva's Journal",
    "Ancient Carving",
    "Ancient Scrawl",
    "Atalui, Blood Priestess",
    "Atazek, Blood Priest",
    "Blood Offering",
    "Cauldron Keeper",
    "Disciple of Atziri",
    "Doryani",
    "Expedition Logbook",
    "Flayed Offering",
    "Gwendolyn Albright",
    "Impaled Offering",
    "Jiquani's Frustration",
    "Jiquani's Rumination",
    "Ketzuli, High Priest of the Sun",
    "Old Carving",
    "Oswald",
    "Oswald's Death Journal",
    "Queen of Filth",
    "Ravaged Corpse",
    "Recent Carving",
    "Rejoice!",
    "Sebastian Carroway",
    "Servi",
    "Stone Tablet",
    "Tonqui, Seer of the Sun",
    "Torn Offering",
    "Freya Hartlin",
    "Krutog, Lord of Kin",
    "Cedrus",
    "Gwennen",
    "Ketzuli, Architect of Time",
    "Mysterious Obelisk",
    "Tujen",
    "Count Geonor",
    "Lachlann of Endless Lament",
    "Count's Journal",
    "Torture Log",
    "Iktab, the Deathlord",
    "The Bloated Miller",
    "The Rust King",
    "Ghostly Voice",
    "Og The Mangler",
    "Bearer Of Penitence",
    "BlackJaw",
    "Captain Hartlin",
    "Imperial Knight",
    "Kabala, Constrictor Queen",
    "Ignagduk, the Bog Witch",
    "Diamora, the Song of Death",
    "The Prisoner",
    "Ursea, The Matron",
    "Phanos, Last Disciple of Auria",
    "Geonor, the Putrid Wolf",
    "The Countess",
    "Rudja, Dread Engineer",
    "Statue of Hillock",
    "Statue of the Vaal Oversoul",
    "Statue of Dominus",
    "Statue of Malachai",
    "Statue of Kitava",
    "Xesht, We That Are One",
    "Asinia, the Praetor's Consort",
    "Draven, the Eternal Praetor",
    "Mektul, the Forgemaster",
    "First Mate",
    "High Priest",
    "Zarokh, the Temporal",
    "The Arbiter of Ash",
    "Mysterious Entity",
    "Lycius, Midnight's Howl",
]);